---
# tasks file for docker-ce-ansible-role

- name: Remove previous docker installation
  yum:
    name: "{{ docker_cleanup_packages_EL }}"
    state: absent
  tags: docker

- name: Install prerequisite packages
  yum:
    name: "{{ docker_prerequisite_packages_EL }}"
    state: present
  tags: docker


- name: Enable additional repository (for RHEL only)
  rhsm_repository:
    name: "rhel-7-server-extras-rpms"
    state: present
  when: ansible_distribution == "RedHat"
  tags: docker

- name: Install additional prerequisite packages (for RHEL only)
  yum:
    name: "{{ docker_prerequisite_packages_EL_RHEL }}"
    state: present
  when: ansible_distribution == "RedHat"
  tags: docker

- name: Import Docker CE repository gpg key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present
  tags: docker

- name: Add Docker CE repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    force: yes
    owner: root
    group: root
    mode: 0644
  tags: docker

- name: Debug docker version
  debug:
    msg: installing docker version - {{ el_docker_version }}
  tags: docker

- name: Install Docker CE
  yum:
    name: docker-ce-{{ el_docker_version }}
    state: present
    update_cache: yes
  register: dockerResult
#  until: '"failed" not in result'
  retries: 3
  delay: 5
  tags: docker