---
# handlers file for docker-ce-ansible-role

- name: Start Docker CE service
  service:
    name: docker
    state: started
  tags: docker

- name: Restart Docker CE service
  service:
    name: docker
    state: restarted
  tags: docker